name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "30 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: equisde
        run: |
          git config --local user.email "kalom4327@gmail.com"
          git config --local user.name "equisde"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "new update"
          git push
